language: r
cache: packages
pandoc_version: 2.1.3

addons:
    apt:
        packages:
            - libopenblas-base
            - libudunits2-dev
            - libv8-dev
            - libprotobuf-dev
            - libprotoc-dev
            - libproj-dev
            - libgeos-dev
            - libgdal-dev
            - protobuf-compiler
            - valgrind
            - libjq-dev
            - netcdf-bin
        brew_packages:
            - udunits
r_github_packages: 
    - tereom/estcomp
    - diegovalle/mxmaps

# repos: 
#   CRAN: https://cran.rstudio.com
#   rforge: http://R-Forge.R-project.org

before_install:
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'
before_script:
    - chmod +x ./_build.sh
    - chmod +x ./_deploy.sh
script:
    - ./_build.sh
    - ./_deploy.sh
