language: r
cache: packages
pandoc_version: 2.1.3

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libopenblas-base
            - libudunits2-dev
            - libv8-dev
            - libprotobuf-dev
            - libprotoc-dev
            - libproj-dev
            - libgeos-dev
            - libgdal-dev
            - protobuf-compiler
            - valgrind
            - libjq-dev
            - netcdf-bin
            - g++-7
        brew_packages:
            - udunits
r_github_packages: 
    - tereom/estcomp
    - diegovalle/mxmaps
    - stan-dev/bayesplot

# repos: 
#   CRAN: https://cran.rstudio.com
#   rforge: http://R-Forge.R-project.org

before_install:
    - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'
    - mkdir -p ~/.R/
    - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
    - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

install: 
    - R -e "install.packages('rstan', 'bookdown')"

before_script:
    - chmod +x ./_build.sh
    - chmod +x ./_deploy.sh

script:
    - ./_build.sh
    - ./_deploy.sh
    - R -e "rstan::stan_version()"
