language: r
cache: packages
pandoc_version: 2.1.3

matrix:
  include:
    - os: linux
      dist: trusty
      r: release
      r_binary_packages:
        - devtools
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      dist: trusty
      r: devel
      r_binary_packages:
        - devtools
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

addons:
    apt:
        packages:
            - libopenblas-base
            - libudunits2-dev
            - libv8-dev
            - libprotobuf-dev
            - libprotoc-dev
            - libproj-dev
            - libgeos-dev
            - libgdal-dev
            - protobuf-compiler
            - valgrind
            - libjq-dev
            - netcdf-bin
        brew_packages:
            - udunits
r_github_packages: 
    - tereom/estcomp
    - diegovalle/mxmaps

# repos: 
#   CRAN: https://cran.rstudio.com
#   rforge: http://R-Forge.R-project.org

before_install:
  - R -e 'install.packages("rgdal", repos=c("http://R-Forge.R-project.org", "http://cran.rstudio.com"))'
    - mkdir -p ~/.R/
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14 = g++-7 -fPIC" >> ~/.R/Makevars; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars; fi
before_script:
    - chmod +x ./_build.sh
    - chmod +x ./_deploy.sh
script:
    - ./_build.sh
    - ./_deploy.sh
